version: "3.7"

services:
  app:
    build:
      context: ./docker/php
      args:
        UID: ${APP_UID}
        GID: ${APP_GID}
    tty: true
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mysql:8.0
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER -p$$MYSQL_PASSWORD

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
