services:
  app:
    build:
      context: ./docker/php81
      args:
        UID: ${APP_UID}
        GID: ${APP_GID}
    tty: true
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      redis:
        condition: service_started

  app-php82:
    build:
      context: ./docker/php82
      args:
        UID: ${APP_UID}
        GID: ${APP_GID}
    tty: true
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      redis:
        condition: service_started
    profiles:
      - app-php82

  app-php83:
    build:
      context: ./docker/php83
      args:
        UID: ${APP_UID}
        GID: ${APP_GID}
    tty: true
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      redis:
        condition: service_started
    profiles:
      - app-php83

  app-php84:
    build:
      context: ./docker/php84
      args:
        UID: ${APP_UID}
        GID: ${APP_GID}
    tty: true
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      redis:
        condition: service_started
    profiles:
      - app-php84

  redis:
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379
