name: Lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2']
        laravel: ['9', '10']

    name: PHP ${{ matrix.php }} + Laravel ${{ matrix.laravel }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php }}
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

      - name: Update Composer to latest version
        run: sudo composer self-update

      - name: Validate composer.json
        run: composer validate

      - name: Install Composer dependencies
        run: |
          composer install --no-interaction
          if [[ "${{ matrix.laravel }}" == '9' ]]; then
            composer update --no-interaction orchestra/testbench:^7.0 --with-all-dependencies
          fi

      - name: Run lint
        run: composer lint
