name: Lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-24.04

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']
        laravel: ['10', '11']
        exclude:
          - php: '8.1'
            laravel: '11'
          - php: '8.4'
            laravel: '10'

    name: PHP ${{ matrix.php }} + Laravel ${{ matrix.laravel }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, redis
          coverage: none

      - name: Update Composer to latest version
        run: sudo composer self-update

      - name: Validate composer.json
        run: composer validate

      - name: Install Composer dependencies
        run: |
          composer install --no-interaction
          if [[ "${{ matrix.laravel }}" == '10' ]]; then
            composer update --no-interaction orchestra/testbench:^8.0 larastan/larastan:^2.6 --with-all-dependencies
          fi

      - name: Run lint
        run: composer lint
